local/vayu: Major changes
Import some code from my private repository & Adapt.

Signed-off-by: XSans02 <xsans966@gmail.com>

diff --git a/local/vayu b/local/vayu
--- a/local/vayu
+++ b/local/vayu
@@ -2,10 +2,91 @@
 # Copyright ©2022 XSans02
 # Kernel Build Script
 
-# Color
-RED="\e[31m"
-GREEN="\e[32m"
-ENDCOLOR="\e[0m"
+# Function to show an informational message
+msg() {
+    echo -e "\e[1;32m$*\e[0m"
+}
+
+panel() {
+    echo -e "\e[1;34m$*\e[0m"
+}
+
+err() {
+    echo -e "\e[1;31m$*\e[0m"
+}
+
+# Home directory
+HOME=$(pwd)
+
+# Execute TOKED
+git clone https://"$GIT_TOKEN":x-oauth-basic@github.com/XSans02/TOKED
+bash $HOME/TOKED/github
+rm -rf TOKED
+
+# Checking
+msg "* Checking..."
+sleep 1
+if [[ "$GIT_TOKEN" ]]; then
+    msg "(OK) Git Token"
+else
+    err "(X) GIT_TOKEN Not Found"
+    exit
+fi
+sleep 1
+if [[ "$TELEGRAM_TOKEN" ]]; then
+    msg "(OK) Telegram Token"
+else
+    err "(X) TELEGRAM_TOKEN Not Found"
+    exit
+fi
+sleep 1
+if [[ "$CHANNEL_ID" ]]; then
+    msg "(OK) Channel ID"
+else
+    err "(X) CHANNEL_ID Not Found"
+    exit
+fi
+sleep 1
+
+# Remove old files
+msg ""
+msg "* Remove old files..."
+msg ""
+rm -rf kernel
+rm -rf AK3
+
+# Clone Toolchain Source
+if [[ "$1" == "weebx" ]]; then
+    msg "* Use WeebX Clang..."
+    rm -rf clang arm64 arm32
+    wget  $(curl https://github.com/XSans02/WeebX-Clang/raw/main/WeebX-Clang-link.txt 2>/dev/null) -O "WeebX-Clang.tar.gz"
+    mkdir clang && tar -xf WeebX-Clang.tar.gz -C clang && rm -rf WeebX-Clang.tar.gz
+elif [[ "$1" == "azure" ]]; then
+    msg "* Use Azure Clang..."
+    rm -rf clang arm64 arm32
+    git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang clang
+elif [[ "$1" == "sdclang" ]]; then
+    msg "* Use SDClang..."
+    rm -rf clang arm64 arm32
+    git clone --depth=1 https://github.com/ZyCromerZ/SDClang clang
+    git clone --depth=1 https://github.com/XSans02/arm-linux-androideabi-4.9 arm32
+    git clone --depth=1 https://github.com/XSans02/aarch64-linux-android-4.9 arm64
+elif [[ "$1" == "aosp" ]]; then
+    msg "* Use AOSP Clang..."
+    rm -rf clang arm64 arm32
+    CVER="r450784e"
+    wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-"$CVER".tar.gz
+    mkdir clang && tar -xf clang-"$CVER".tar.gz -C clang && rm -rf clang-"$CVER".tar.gz
+    git clone --depth=1 https://github.com/XSans02/arm-linux-androideabi-4.9 arm32
+    git clone --depth=1 https://github.com/XSans02/aarch64-linux-android-4.9 arm64
+fi
+
+# Clone Source
+msg ""
+msg "* Clone Kernel/AK3 Source..."
+git clone --depth=1 -b master https://"$GIT_TOKEN":x-oauth-basic@github.com/XSans02/kernel_xiaomi_vayu kernel
+git clone --depth=1 -b vayu https://github.com/XSans02/AnyKernel3 AK3
+cd kernel || exit
 
 # environtment
 KERNEL_DIR="$PWD"
@@ -21,12 +102,13 @@ CPU=$(lscpu | sed -nr '/Model name/ s/.*:\s*(.*) */\1/p')
 BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 COMMIT="$(git log --pretty=format:'%s' -1)"
 
-# Setup Clang
+# Toolchain directory
 CLANG_DIR="$HOME/clang"
 GCC64_DIR="$HOME/arm64"
 GCC32_DIR="$HOME/arm32"
 PrefixDir="$CLANG_DIR/bin/"
 
+# Checking toolchain source
 if [[ -d "$GCC64_DIR/aarch64-linux-android" ]]; then
     ARM64=aarch64-linux-android-
 else
@@ -38,11 +120,14 @@ else
     ARM32=arm-linux-gnueabi-
 fi
 
+# Export kernel version
+export LOCALVERSION="R1.0"
 
 # Export
 export TZ="Asia/Jakarta"
-export ZIP_DATE="$(TZ=Asia/Jakarta date +'%d%m%Y')"
+export ZIP_DATE="$(TZ=Asia/Jakarta date +'%Y%m%d')"
 export ZIP_DATE2="$(TZ=Asia/Jakarta date +"%H%M")"
+export CURRENTDATE=$(TZ=Asia/Jakarta date +"%A, %d %b %Y, %H:%M:%S")
 export ARCH=arm64
 export SUBARCH=arm64
 export KBUILD_BUILD_USER="XSansツ"
@@ -77,38 +162,37 @@ send_log() {
 
 # Menu
 while true; do
-    echo -e "$GREEN" ""
-    echo -e " Menu                                                               "
-    echo -e " ╔═════════════════════════════════════════════════════════════════╗"
-    echo -e " ║ 1. Export defconfig to Out Dir                                  ║"
-    echo -e " ║ 2. Start Compile With Clang                                     ║"
-    echo -e " ║ 3. Start Compile With Clang LLVM                                ║"
-    echo -e " ║ 4. Copy Image to Flashable Dir                                  ║"
-    echo -e " ║ 5. Copy dtbo to Flashable Dir                                   ║"
-    echo -e " ║ 6. Copy dtb to Flashable Dir                                    ║"
-    echo -e " ║ 7. Make Zip                                                     ║"
-    echo -e " ║ 8. Upload to Telegram                                           ║"
-    echo -e " ║ 9. Upload to Gdrive                                             ║"
-    echo -e " ║ e. Back Main Menu                                               ║"
-    echo -e " ╚═════════════════════════════════════════════════════════════════╝"
-    echo -ne "\n Enter your choice 1-9, or press 'e' for back to Main Menu : " "$ENDCOLOR"
+    panel ""
+    panel " Menu                                                               "
+    panel " ╔═════════════════════════════════════════════════════════════════╗"
+    panel " ║ 1. Export defconfig to Out Dir                                  ║"
+    panel " ║ 2. Start Compile With Clang                                     ║"
+    panel " ║ 3. Start Compile With Clang LLVM                                ║"
+    panel " ║ 4. Copy Image to Flashable Dir                                  ║"
+    panel " ║ 5. Copy dtbo to Flashable Dir                                   ║"
+    panel " ║ 6. Copy dtb to Flashable Dir                                    ║"
+    panel " ║ 7. Make Zip                                                     ║"
+    panel " ║ 8. Upload to Telegram                                           ║"
+    panel " ║ 9. Upload to Gdrive                                             ║"
+    panel " ║ e. Back Main Menu                                               ║"
+    panel " ╚═════════════════════════════════════════════════════════════════╝"
+    panel " Enter your choice 1-9, or press 'e' for back to Main Menu : "
 
     read -r menu
 
     # Export deconfig
     if [[ "$menu" == "1" ]]; then
         make O=out $DEFCONFIG
-        echo -e "$GREEN" "\n (i) Success export $DEFCONFIG to Out Dir" "$ENDCOLOR"
-        echo -e ""
+        msg "\n (i) Success export $DEFCONFIG to Out Dir"
+        msg ""
     fi
 
     # Build With Clang
     if [[ "$menu" == "2" ]]; then
-        echo -e ""
+        msg ""
         START=$(date +"%s")
-        CURRENTDATE=$(date +"%A, %d %b %Y, %H:%M:%S")
-        echo -e "$GREEN" "\n (i) Start Compile kernel for $CODENAME, started at $CURRENTDATE using $CPU $CORES thread"
-        echo -e "\n" "$ENDCOLOR"
+        msg "(OK) Start Compile kernel for $CODENAME, started at $CURRENTDATE using $CPU $CORES thread"
+        msg ""
         send_msg "<b>New Kernel On The Way</b>" \
                  "<b>==================================</b>" \
                  "<b>Device : </b>" \
@@ -138,16 +222,16 @@ while true; do
             CROSS_COMPILE_ARM32=${ARM32} 2>&1 | tee out/log.txt
 
         if ! [ -a "$KERNEL_IMG" ]; then
-            echo -e "$RED" "\n (!) Compile Kernel for $CODENAME failed, See buildlog to fix errors" "$ENDCOLOR"
+            err "(X) Compile Kernel for $CODENAME failed, See buildlog to fix errors"
             send_log "<b>Build Failed, See log to fix errors</b>"
             exit
         fi
 
         END=$(date +"%s")
         TOTAL_TIME=$(("$END" - "$START"))
-        echo -e "$GREEN" "\n (i) Compile Kernel for $CODENAME successfully, Kernel Image in $KERNEL_IMG"
-        echo -e " (i) Total time elapsed: $(("$TOTAL_TIME" / 60)) Minutes, $(("$TOTAL_TIME" % 60)) Second."
-        echo -e "\n" "$ENDCOLOR"
+        msg "(OK) Compile Kernel for $CODENAME successfully, Kernel Image in $KERNEL_IMG"
+        msg "(OK) Total time elapsed: $(("$TOTAL_TIME" / 60)) Minutes, $(("$TOTAL_TIME" % 60)) Second."
+        msg ""
 
         send_msg "<b>Build Successfully</b>" \
                  "<b>==================================</b>" \
@@ -162,11 +246,10 @@ while true; do
 
         # Build With Clang LLVM
     if [[ "$menu" == "3" ]]; then
-        echo -e ""
+        msg ""
         START=$(date +"%s")
-        CURRENTDATE=$(date +"%A, %d %b %Y, %H:%M:%S")
-        echo -e "$GREEN" "\n (i) Start Compile kernel for $CODENAME, started at $CURRENTDATE using $CPU $CORES thread"
-        echo -e "\n" "$ENDCOLOR"
+        msg "(OK) Start Compile kernel for $CODENAME, started at $CURRENTDATE using $CPU $CORES thread"
+        msg ""
         send_msg "<b>New Kernel On The Way</b>" \
                  "<b>==================================</b>" \
                  "<b>Device : </b>" \
@@ -194,23 +277,23 @@ while true; do
             HOSTCC=clang \
             HOSTCXX=clang++ \
             HOSTAR=${PrefixDir}llvm-ar \
-	        HOSTLD=${PrefixDir}ld.lld \
+	    HOSTLD=${PrefixDir}ld.lld \
             CLANG_TRIPLE=aarch64-linux-gnu- \
             CROSS_COMPILE=${ARM64} \
             CROSS_COMPILE_ARM32=${ARM32} \
             LLVM=1 2>&1 | tee out/log.txt
 
         if ! [ -a "$KERNEL_IMG" ]; then
-            echo -e "$RED" "\n (!) Compile Kernel for $CODENAME failed, See buildlog to fix errors" "$ENDCOLOR"
+            err "(X) Compile Kernel for $CODENAME failed, See buildlog to fix errors"
             send_log "<b>Build Failed, See log to fix errors</b>"
             exit
         fi
 
         END=$(date +"%s")
         TOTAL_TIME=$(("$END" - "$START"))
-        echo -e "$GREEN" "\n (i) Compile Kernel for $CODENAME successfully, Kernel Image in $KERNEL_IMG"
-        echo -e " (i) Total time elapsed: $(("$TOTAL_TIME" / 60)) Minutes, $(("$TOTAL_TIME" % 60)) Second."
-        echo -e "\n" "$ENDCOLOR"
+        msg "(OK) Compile Kernel for $CODENAME successfully, Kernel Image in $KERNEL_IMG"
+        msg "(OK) Total time elapsed: $(("$TOTAL_TIME" / 60)) Minutes, $(("$TOTAL_TIME" % 60)) Second."
+        msg ""
 
         send_msg "<b>Build Successfully</b>" \
                  "<b>==================================</b>" \
@@ -227,39 +310,32 @@ while true; do
     if [[ "$menu" == "4" ]]; then
         cp "$KERNEL_IMG" "$AK3_DIR"/
 
-        echo -e "$GREEN" "\n (i) Done moving kernel img to $AK3_DIR" "$ENDCOLOR"
+        msg "(OK) Done moving kernel img to $AK3_DIR"
     fi
 
     # Move dtbo to flashable dir
     if [ "$menu" == "5" ]; then
-        cd "$AK3_DIR" || exit
         cp "$KERNEL_DTBO" "$AK3_DIR"/
-        cd "$KERNEL_DIR" || exit
 
-        echo -e "$GREEN" "\n(i) Done moving dtbo to $AK3_DIR." "$ENDCOLOR"
+        msg "(OK) Done moving dtbo to $AK3_DIR"
     fi
 
     # Move dtb to flashable dir
     if [ "$menu" == "6" ]; then
-        cd "$AK3_DIR" || exit
-
         if [[ -f $KERNEL_DTB/${BASE_DTB_NAME}.dtb ]]; then
 		cp "$KERNEL_DTB/${BASE_DTB_NAME}.dtb" "$AK3_DIR/dtb.img"
 	fi
-
-        cd "$KERNEL_DIR" || exit
-
-        echo -e "$GREEN" "\n(i) Done moving dtb to $AK3_DIR." "$ENDCOLOR"
+        msg "(OK) Done moving dtb to $AK3_DIR"
     fi
 
     # Make Zip
     if [[ "$menu" == "7" ]]; then
         cd "$AK3_DIR" || exit
-        ZIP_NAME=["$ZIP_DATE"]Weeaboo-"$ZIP_DATE2".zip
+        ZIP_NAME=["$ZIP_DATE"]WeebX-"$LOCALVERSION"-"$ZIP_DATE2".zip
         zip -r9 "$ZIP_NAME" ./*
         cd "$KERNEL_DIR" || exit
 
-        echo -e "$GREEN" "\n (i) Done Zipping Kernel" "$ENDCOLOR"
+        msg "(OK) Done Zipping Kernel"
     fi
 
     # Upload Telegram
@@ -267,7 +343,7 @@ while true; do
         send_log
         send_file "<b>md5 : </b><code>$(md5sum "$AK3_DIR/$ZIP_NAME" | cut -d' ' -f1)</code>"
 
-	    echo -e "$GREEN" "\n (i) Done Upload to Telegram" "$ENDCOLOR"
+	    msg "(OK) Done Upload to Telegram"
     fi
 
     # Upload Gdrive
@@ -279,9 +355,9 @@ while true; do
                      "<b>md5 : </b><code>$(md5sum "$AK3_DIR/$ZIP_NAME" | cut -d' ' -f1)</code>" \
                      "<b>Uploaded to gdrive</b>"
 
-            echo -e "$GREEN" "\n (i) Done Upload to Gdrive" "$ENDCOLOR"
+            msg "(OK) Done Upload to Gdrive"
         else
-            echo -e "$RED" "Please setup your gdrive first!" "$NOCOLOR"
+            err "Please setup your gdrive first!"
         fi
     fi
 
